// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvpnX7bnRpK5MxbM3KgHsLPVk5HA03DI',
    appId: '1:452505538258:web:2e84b530a61e883def670b',
    messagingSenderId: '452505538258',
    projectId: 'poppy-c9de9',
    authDomain: 'poppy-c9de9.firebaseapp.com',
    storageBucket: 'poppy-c9de9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbZvEC3wlGmpILT1i4029FaBir3ImLnYE',
    appId: '1:452505538258:android:d9e75c161c6be421ef670b',
    messagingSenderId: '452505538258',
    projectId: 'poppy-c9de9',
    storageBucket: 'poppy-c9de9.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAappRVqQ1S5JKV3KMZPoPftr0xMWqvdHk',
    appId: '1:452505538258:ios:a3b6aaa03a010747ef670b',
    messagingSenderId: '452505538258',
    projectId: 'poppy-c9de9',
    storageBucket: 'poppy-c9de9.appspot.com',
    iosClientId: '452505538258-46ntv45v3tr7h021g6rcfjtbaq6kitao.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
